version: '3.8'

services:
  app_todo:
    build:
      context: .
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://dbtodo:3306/lista-de-tareas
      DB_USER: root
      DB_PASSWORD: Meteor93!
    restart: always
    depends_on:
      dbtodo:
        condition: service_healthy

  dbtodo:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Meteor93!
      MYSQL_DATABASE: lista-de-tareas
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
      interval: 30s   # Intervalo de espera más largo
      timeout: 10s    # Mayor tiempo de espera
      retries: 5      # Más intentos antes de marcarlo como no saludable
