version: '3'

services:
  app_todo:
    container_name: app_todo
    build:
      context: .
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_HOST: dbtodo
      DB_NAME: lista-de-tareas
      DB_PASSWORD: Meteor93!
      DB_PORT: 3306
      DB_USER: root
    restart: always
    depends_on:
      dbtodo:
        condition: service_healthy
  dbtodo:
    container_name: dbtodo
    image: mysql:9.1.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Meteor93!
      MYSQL_DATABASE: lista-de-tareas
      MYSQL_PASSWORD: Meteor93!
    restart: on-failure
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5